import type { DashboardMetrics, Transaction, Game, User, Admin } from "@/types"

export const mockDashboardMetrics: DashboardMetrics = {
  totalUsers: 12543,
  activeUsers: 8234,
  totalRevenue: 1245678,
  pendingWithdrawals: 45230,
  activeGames: 12,
}

export const mockRecentActivity: Transaction[] = [
  {
    id: "1",
    userId: "user_001",
    userName: "John Doe",
    amount: 5000,
    type: "credit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    description: "Game winnings",
  },
  {
    id: "2",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 2500,
    type: "debit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    description: "Withdrawal request",
  },
  {
    id: "3",
    userId: "user_003",
    userName: "Mike Johnson",
    amount: 1000,
    type: "credit",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    description: "Deposit",
  },
  {
    id: "4",
    userId: "user_004",
    userName: "Sarah Williams",
    amount: 7500,
    type: "credit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    description: "Game winnings",
  },
  {
    id: "5",
    userId: "user_005",
    userName: "David Brown",
    amount: 3200,
    type: "debit",
    status: "failed",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    description: "Withdrawal request",
  },
]

export const mockChartData = {
  gameParticipation: [
    { date: "Mon", participants: 1200 },
    { date: "Tue", participants: 1800 },
    { date: "Wed", participants: 1500 },
    { date: "Thu", participants: 2200 },
    { date: "Fri", participants: 2800 },
    { date: "Sat", participants: 3200 },
    { date: "Sun", participants: 2900 },
  ],
  transactions: [
    { date: "Mon", amount: 45000 },
    { date: "Tue", amount: 52000 },
    { date: "Wed", amount: 48000 },
    { date: "Thu", amount: 61000 },
    { date: "Fri", amount: 72000 },
    { date: "Sat", amount: 85000 },
    { date: "Sun", amount: 78000 },
  ],
}

export const mockGames: Game[] = [
  {
    id: "game_001",
    title: "Lucky Draw Mega",
    description: "Win big prizes in our mega lucky draw event",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    prizePool: 50000,
    status: "upcoming" as const,
    participants: 0,
  },
  {
    id: "game_002",
    title: "Weekend Jackpot",
    description: "Special weekend jackpot with amazing rewards",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    prizePool: 75000,
    status: "live" as const,
    participants: 1234,
  },
  {
    id: "game_003",
    title: "Daily Fortune",
    description: "Daily lucky draw with instant prizes",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    prizePool: 25000,
    status: "completed" as const,
    participants: 856,
  },
  {
    id: "game_004",
    title: "Golden Hour Special",
    description: "Limited time golden hour event",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
    prizePool: 100000,
    status: "upcoming" as const,
    participants: 0,
  },
  {
    id: "game_005",
    title: "Midnight Madness",
    description: "Exclusive midnight lucky draw",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    prizePool: 60000,
    status: "completed" as const,
    participants: 2341,
  },
]

export const mockUsers: User[] = [
  {
    id: "user_001",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+1234567890",
    balance: 15000,
    kycStatus: "verified",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: "user_002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+1234567891",
    balance: 8500,
    kycStatus: "verified",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: "user_003",
    name: "Mike Johnson",
    email: "mike.j@example.com",
    phone: "+1234567892",
    balance: 3200,
    kycStatus: "pending",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: "user_004",
    name: "Sarah Williams",
    email: "sarah.w@example.com",
    phone: "+1234567893",
    balance: 22000,
    kycStatus: "verified",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
  },
  {
    id: "user_005",
    name: "David Brown",
    email: "david.b@example.com",
    phone: "+1234567894",
    balance: 500,
    kycStatus: "rejected",
    isActive: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "user_006",
    name: "Emily Davis",
    email: "emily.d@example.com",
    phone: "+1234567895",
    balance: 12500,
    kycStatus: "verified",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
]

export const mockAdmins: Admin[] = [
  {
    id: "admin_001",
    email: "super@luckybag.com",
    name: "Super Admin",
    role: "super_admin",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "admin_002",
    email: "games@luckybag.com",
    name: "Game Manager",
    role: "game_manager",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "admin_003",
    email: "users@luckybag.com",
    name: "User Manager",
    role: "user_manager",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "admin_004",
    email: "finance@luckybag.com",
    name: "Finance Admin",
    role: "finance_admin",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "admin_005",
    email: "support@luckybag.com",
    name: "Support Admin",
    role: "support_admin",
    isActive: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
]

export const mockAllTransactions: Transaction[] = [
  ...mockRecentActivity,
  {
    id: "6",
    userId: "user_006",
    userName: "Emily Davis",
    amount: 4500,
    type: "credit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    description: "Game winnings",
  },
  {
    id: "7",
    userId: "user_001",
    userName: "John Doe",
    amount: 1500,
    type: "debit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    description: "Withdrawal request",
  },
  {
    id: "8",
    userId: "user_003",
    userName: "Mike Johnson",
    amount: 2000,
    type: "credit",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    description: "Deposit",
  },
]
