import type { DashboardMetrics, Transaction, Game, User, Admin, Activity } from "@/types"

export const mockDashboardMetrics: DashboardMetrics = {
  totalUsers: 12543,
  activeUsers: 8234,
  totalRevenue: 1245678,
  pendingWithdrawals: 45230,
  activeGames: 12,
}

export const mockRecentActivity: Transaction[] = [
  {
    id: "1",
    userId: "user_001",
    userName: "John Doe",
    amount: 5000,
    type: "credit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    description: "Game winnings",
  },
  {
    id: "2",
    userId: "user_002",
    userName: "Jane Smith",
    amount: 2500,
    type: "debit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    description: "Withdrawal request",
  },
  {
    id: "3",
    userId: "user_003",
    userName: "Mike Johnson",
    amount: 1000,
    type: "credit",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    description: "Deposit",
  },
  {
    id: "4",
    userId: "user_004",
    userName: "Sarah Williams",
    amount: 7500,
    type: "credit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    description: "Game winnings",
  },
  {
    id: "5",
    userId: "user_005",
    userName: "David Brown",
    amount: 3200,
    type: "debit",
    status: "failed",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    description: "Withdrawal request",
  },
]

export const mockActivityFeed: Activity[] = [
  {
    id: "act_1",
    title: "Draw completed",
    description: "Mega Fortune Weekly — 3 winners selected",
    type: "draw_completed",
    timestamp: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: "act_2",
    title: "New user registered",
    description: "LBG-41026677 · yuki.t@example.com",
    type: "user_registered",
    timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
  },
  {
    id: "act_3",
    title: "Wallet credited",
    description: "$500 added to LBG-20341188 (Jordan Lee)",
    type: "wallet_credited",
    timestamp: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
  },
  {
    id: "act_4",
    title: "Game scheduled",
    description: "Summer Special Raffle — Draw: Jul 15 18:00",
    type: "game_scheduled",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
  {
    id: "act_5",
    title: "Admin login",
    description: "ops@luckybag.io · IP 192.168.1.4",
    type: "admin_login",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "act_6",
    title: "Withdrawal processed",
    description: "$1,250 debited from LBG-11874422 (Priya Sharma)",
    type: "withdrawal_processed",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
]


export const mockChartData = {
  gameParticipation: [
    { date: "Mon", participants: 1200, newUsers: 150 },
    { date: "Tue", participants: 1800, newUsers: 230 },
    { date: "Wed", participants: 1500, newUsers: 180 },
    { date: "Thu", participants: 2200, newUsers: 320 },
    { date: "Fri", participants: 2800, newUsers: 410 },
    { date: "Sat", participants: 3200, newUsers: 550 },
    { date: "Sun", participants: 2900, newUsers: 480 },
  ],
  transactions: [
    { date: "Mon", amount: 45000, withdrawals: 12000 },
    { date: "Tue", amount: 52000, withdrawals: 15000 },
    { date: "Wed", amount: 48000, withdrawals: 18000 },
    { date: "Thu", amount: 61000, withdrawals: 14000 },
    { date: "Fri", amount: 72000, withdrawals: 22000 },
    { date: "Sat", amount: 85000, withdrawals: 31000 },
    { date: "Sun", amount: 78000, withdrawals: 25000 },
  ],
}

export const mockGames: Game[] = [
  {
    id: "game_001",
    title: "Mega Fortune Weekly",
    description: "Win big prizes in our mega lucky draw event",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    prizePool: 5000,
    status: "live" as const,
    participants: 0,
    interval: "168h",
    winPercentage: 12,
    maxWinners: 3,
  },
  {
    id: "game_002",
    title: "Daily Jackpot Rush",
    description: "Special weekend jackpot with amazing rewards",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    prizePool: 1000,
    status: "live" as const,
    participants: 1234,
    interval: "24h",
    winPercentage: 8,
    maxWinners: 1,
  },
  {
    id: "game_003",
    title: "Monthly Bonanza Draw",
    description: "Daily lucky draw with instant prizes",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    prizePool: 25000,
    status: "upcoming" as const,
    participants: 856,
    interval: "720h",
    winPercentage: 5,
    maxWinners: 5,
  },
  {
    id: "game_004",
    title: "Summer Special Raffle",
    description: "Limited time golden hour event",
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    endTime: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
    prizePool: 10000,
    status: "upcoming" as const,
    participants: 0,
    interval: "One-time",
    winPercentage: 15,
    maxWinners: 2,
  },
  {
    id: "game_005",
    title: "Spring Classic 2026",
    description: "Exclusive midnight lucky draw",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    prizePool: 8000,
    status: "completed" as const,
    participants: 2341,
    interval: "One-time",
    winPercentage: 10,
    maxWinners: 4,
  },
  {
    id: "game_006",
    title: "New Year Lucky Draw",
    description: "Start the year with a bang",
    startTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    endTime: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
    prizePool: 15000,
    status: "completed" as const,
    participants: 5120,
    interval: "One-time",
    winPercentage: 7,
    maxWinners: 3,
  },
]

export const mockUsers: User[] = [
  {
    id: "user_47852255",
    name: "Marcus Williams",
    email: "marcus.w@example.com",
    phone: "+1 555-0101",
    balance: 2340.00,
    kycStatus: "verified",
    emailVerified: true,
    smsVerified: true,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    id: "user_11874422",
    name: "Priya Sharma",
    email: "priya.sh@example.com",
    phone: "+1 555-0187",
    balance: 8750.00,
    kycStatus: "verified",
    emailVerified: true,
    smsVerified: false,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: "user_20341188",
    name: "Jordan Lee",
    email: "jordan.lee@example.com",
    phone: "+1 555-2034",
    balance: 450.00,
    kycStatus: "verified",
    emailVerified: true,
    smsVerified: true,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: "user_22103344",
    name: "Fatima Al-Hassan",
    email: "fatima.h@example.com",
    phone: "+1 555-2210",
    balance: 1200.00,
    kycStatus: "pending",
    emailVerified: false,
    smsVerified: false,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
  },
  {
    id: "user_33011100",
    name: "Devon Brooks",
    email: "devon.b@example.com",
    phone: "+1 555-3301",
    balance: 12000.00,
    kycStatus: "verified",
    emailVerified: true,
    smsVerified: true,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "user_41026677",
    name: "Yuki Tanaka",
    email: "yuki.t@example.com",
    phone: "+1 555-4102",
    balance: 300.00,
    kycStatus: "pending",
    emailVerified: true,
    smsVerified: false,
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
  },
]

export const mockAdmins: Admin[] = [
  {
    id: "admin_001",
    email: "super@luckybag.com",
    name: "Super Admin",
    role: "super_admin",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 365).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "admin_002",
    email: "games@luckybag.com",
    name: "Game Manager",
    role: "game_manager",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "admin_003",
    email: "users@luckybag.com",
    name: "User Manager",
    role: "user_manager",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "admin_004",
    email: "finance@luckybag.com",
    name: "Finance Admin",
    role: "finance_admin",
    isActive: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "admin_005",
    email: "support@luckybag.com",
    name: "Support Admin",
    role: "support_admin",
    isActive: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    lastLogin: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
]

export const mockAllTransactions: Transaction[] = [
  ...mockRecentActivity,
  {
    id: "6",
    userId: "user_006",
    userName: "Emily Davis",
    amount: 4500,
    type: "credit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    description: "Game winnings",
  },
  {
    id: "7",
    userId: "user_001",
    userName: "John Doe",
    amount: 1500,
    type: "debit",
    status: "completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    description: "Withdrawal request",
  },
  {
    id: "8",
    userId: "user_003",
    userName: "Mike Johnson",
    amount: 2000,
    type: "credit",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    description: "Deposit",
  },
]
